branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - main
  - next
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: 'conventionalcommits'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/npm'
    - tarballDir: dist
  - - '@semantic-release/github'
    - successComment: false
      failComment: false
      assets: 'dist/*.tgz'
