branches:
  - '+([0-9])?(.{+([0-9]),x}).x'
  - main
  - next
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
  - name: 'feat/*'
    channel: 'feat-${name.replace(/^feat\//, "")}'
    prerelease: 'feat-${name.replace(/^feat\//, "")}'
  - name: 'feature/*'
    channel: 'feat-${name.replace(/^feature\//, "")}'
    prerelease: 'feat-${name.replace(/^feature\//, "")}'

plugins:
  - - '@semantic-release/commit-analyzer'
    - preset: 'conventionalcommits'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/npm'
    - tarballDir: dist
  - - '@semantic-release/github'
    - successComment: false
      failComment: false
      assets: 'dist/*.tgz'
